language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3

before-install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - composer check
  - composer test

env:
    - CODECOV_TOKEN=<8bc61918-49c0-44d4-a028-cb66b7c742be>

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: dev@livecommerce.com.br